version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: network-scanner-db
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=network_scanner
    networks:
      - network-scanner-net

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: network-scanner-backend
    restart: unless-stopped
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=network_scanner
      - CORS_ORIGINS=http://localhost:3000,http://localhost
    depends_on:
      - mongodb
    networks:
      - network-scanner-net
    # Required for network scanning
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8001
    container_name: network-scanner-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - network-scanner-net

volumes:
  mongodb_data:
    driver: local

networks:
  network-scanner-net:
    driver: bridge
